# Generated by Django 4.2.18 on 2025-09-11 02:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=255)),
                ('cpu', models.CharField(max_length=255)),
                ('ram', models.CharField(max_length=255)),
                ('stockage', models.CharField(max_length=255)),
                ('graphic', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('ancien_prix', models.PositiveIntegerField(blank=True, null=True)),
                ('nouveau_prix', models.PositiveIntegerField()),
                ('est_promo', models.BooleanField(default=False)),
                ('est_pc', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='produits/')),
                ('date_insertion', models.DateTimeField(auto_now_add=True)),
                ('marque', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marque', to='vente_pc.marque')),
            ],
            options={
                'ordering': ['-date_insertion'],
            },
        ),
    ]
