# Generated by Django 4.2.18 on 2025-09-11 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vente_pc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='graphic',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
