# Generated by Django 4.2.18 on 2025-09-11 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vente_pc', '0002_alter_produit_graphic'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='prix_promo',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
