# Generated by Django 4.2.18 on 2025-09-11 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vente_pc', '0003_produit_prix_promo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produit',
            options={'ordering': ['-date_insertion', '-marque']},
        ),
    ]
