# Generated by Django 4.2.18 on 2025-09-11 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vente_pc', '0004_alter_produit_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='ancien_prix',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix_promo',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
