# Generated by Django 4.2.18 on 2025-09-11 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vente_pc', '0005_alter_produit_ancien_prix_alter_produit_prix_promo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='ancien_prix',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix_promo',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
