# Generated by Django 4.2.18 on 2025-09-13 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vente_pc', '0006_alter_produit_ancien_prix_alter_produit_prix_promo'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='est_vendue',
            field=models.BooleanField(default=False),
        ),
    ]
