# Generated by Django 4.2.18 on 2025-09-14 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vente_pc', '0007_produit_est_vendue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('tel', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='staff/')),
                ('date_insertion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-nom'],
            },
        ),
    ]
