# Generated by Django 4.2.18 on 2025-09-14 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vente_pc', '0008_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='alias',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
