# Generated by Django 4.2.18 on 2025-09-16 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vente_pc', '0009_staff_alias'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
                ('date_insertion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_insertion'],
            },
        ),
    ]
