# Generated by Django 4.2.18 on 2025-09-16 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vente_pc', '0010_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='produits/'),
        ),
        migrations.AddField(
            model_name='produit',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='produits/'),
        ),
    ]
