# Generated by Django 4.2.18 on 2025-09-18 10:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vente_pc', '0011_produit_image2_produit_image3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forfait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('prix', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vendeur',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('pays', models.CharField(default='Cameroun', max_length=200)),
                ('tel', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('mdp', models.CharField(max_length=255)),
                ('frais', models.PositiveIntegerField()),
                ('date_insertion', models.DateTimeField(auto_now_add=True)),
                ('date_exp', models.DateField(blank=True, null=True, verbose_name='Date expiration')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('forfait', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='vente_pc.forfait')),
            ],
            options={
                'ordering': ['-date_insertion'],
            },
        ),
        migrations.AddField(
            model_name='produit',
            name='vendeur',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='vente_pc.vendeur'),
        ),
    ]
