# Generated by Django 4.2.18 on 2025-09-18 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vente_pc', '0012_forfait_vendeur_produit_vendeur'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendeur',
            name='jours',
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
    ]
