# Generated by Django 4.2.18 on 2025-09-18 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vente_pc', '0013_vendeur_jours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendeur',
            name='logo',
            field=models.ImageField(blank=True, default='images/no_logo.jpg', null=True, upload_to='logos/'),
        ),
    ]
