# Generated by Django 4.2.18 on 2025-09-18 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vente_pc', '0014_alter_vendeur_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendeur',
            name='jours',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
