# Generated by Django 4.2.18 on 2025-09-18 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vente_pc', '0016_alter_vendeur_jours'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendeur',
            name='ville',
            field=models.CharField(default='Douala', max_length=255),
        ),
    ]
