# Generated by Django 4.2.18 on 2025-09-18 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vente_pc', '0017_vendeur_ville'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendeur',
            name='pays',
        ),
        migrations.RemoveField(
            model_name='vendeur',
            name='ville',
        ),
    ]
