# Generated by Django 4.2.18 on 2025-09-18 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vente_pc', '0018_remove_vendeur_pays_remove_vendeur_ville'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='Cameroun', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='Douala', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='vendeur',
            name='pays',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='vente_pc.pays'),
        ),
        migrations.AddField(
            model_name='vendeur',
            name='ville',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='vente_pc.ville'),
        ),
    ]
