# Generated by Django 4.2.18 on 2025-09-18 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vente_pc', '0019_pays_ville_vendeur_pays_vendeur_ville'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendeur',
            name='jours',
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
    ]
