# Generated by Django 4.2.18 on 2025-09-21 11:29

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('vente_pc', '0021_alter_vendeur_jours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='image3',
        ),
        migrations.AlterField(
            model_name='produit',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=75, scale=None, size=[500, 500], upload_to='produits/'),
        ),
    ]
