# Generated by Django 4.2.18 on 2025-09-21 11:31

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('vente_pc', '0022_remove_produit_image2_remove_produit_image3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='image2',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=75, scale=None, size=[500, 500], upload_to='produits/'),
        ),
        migrations.AddField(
            model_name='produit',
            name='image3',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=75, scale=None, size=[500, 500], upload_to='produits/'),
        ),
    ]
