# Generated by Django 4.2.18 on 2025-09-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vente_pc', '0023_produit_image2_produit_image3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendeur',
            name='jours',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
