# Generated by Django 4.2.18 on 2025-09-24 14:07

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vente_pc', '0025_alter_produit_image_alter_produit_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='vendeur',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, default='images/no_logo.jpg', max_length=255, null=True, verbose_name='logo'),
        ),
    ]
